### PR TITLE
chore: uneject

### PR DESCRIPTION
**Pull request by ismay**
Todo

- [x] cli-style
- [x] dotfiles
- [x] put back src files
- [x] public folder
- [x] check package.json (remove unused dependencies)
- [x] working bundling
- [x] i18n folder
- [x] config folder
- [x] scripts folder
- [x] .env files for api discovery
- [x] .github folder
- [x] enable tests
- [x] enable travis (and cli-style)
- [x] update readme
- [x] move to static manifest.json (remove d2-manifest)
- [x] check the scripts in package.json, make sure all are still used
- [x] lodash imported explicitly, rather than from window (core-resources)

Follow up issues

- Fix eslint `disable max-params` comments
- There is a jsdoc generating script. Generating documentation is not something we do with all of our other apps, though I have seen it for d2 I think. The docs don't seem to be hosted anywhere. I think it'd be easy for the docs to fall out of maintenance if they're not actively used and maintained. Maybe we should formally decide to do this for all apps, or none? As otherwise it might seem like a less coherent ecosystem.

Notes

- renamed user-app component to app to align with naming in other apps
- removed babel-polyfill. I don't think we need it, as we're not supporting IE anymore. Create react app ships with react-app-polyfill if you do still support IE, but otherwise language features will be picked up from the browserslist (that's how I read this doc at least: https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill)

Check when reviewing

- No longer calling `serviceWorker.register()` after all initialisation, but at the end of the init script (so it'll run before all initialisation is done). Should just cache static assets, so I think it should be fine at any time.
- For this app, like with the others, moved to unversioned endpoints
- Renamed `root` to `roots` in `components/SearchableOrgUnitTree.js`. It seems like a typo and otherwise it won't compile. Weird thing is that on master it _does_ compile, but I assume that's because of a difference in linter settings? See: https://github.com/dhis2/user-app/blob/3ec64fb491a7f8fe32707be957960ebfeefd5b89/src/components/SearchableOrgUnitTree.js#L194 https://github.com/dhis2/user-app/blob/3ec64fb491a7f8fe32707be957960ebfeefd5b89/src/components/SearchableOrgUnitTree.js#L201

### CODE REVIEW

**Comment by varl** [comment]
> * 
> 
> * Lodash imported from window (is that a core-resources thing?)

Yes. It needs to be bundled if it's used.

**Comment by ismay** [comment]
> Yes. It needs to be bundled if it's used.

Allright, bundling and explicitly importing it now.

**Comment by varl** [comment]
If it's alright with you I'd like to wait with merging until @HendrikThePendric can take a look at this as well.

**Comment by ismay** [comment]
Yeah I think that's a good idea

**Comment by ismay** [comment]
Just asking for your review as well @HendrikThePendric, since you've worked on this app the most. Let me know what you think

**Comment by HendrikThePendric** [comment]
> I just did a commit that removes two unneeded dependencies
OK reversed that one, because these were peer dependencies of the d2-ui table component🥇

**Comment by ismay** [comment]
> jsdoc: I actually added all of this as a result of a misunderstanding. This was my first app for DHIS2 and when I was asked to "add documentation" I thought I needed to jsdoc based docs, but I should have just added to the user-documentation. Personally, I think it might be best to remove it all together. It just clutters the code and is a pain to maintain. But this can be done in a separate branch/jira-issue. And let's check with @varl first, he might want to keep it.

Sounds good. I'd prefer to handle it separately as well.

> I just did a commit that removes two unneeded dependencies
OK reversed that one, because these were peer dependencies of the d2-ui table component🥇

Yeah annoying, luckily, as soon as we upgrade and remove those dependencies we can leave that behind us. I also didn't see them listed whilst installing, so I wonder if they're properly specified as peer dependencies.

> renaming root to roots: glad the linter picked up on this now. These two references to root should have been changed to roots a long time ago edf3989. It completely baffled me at first why this component didn't always have disabled buttons due to this mistake. I looked into it and it is due to this browser behavior. So in my case, I have a <div id="root"></div> which you can access as window.root. So !root is always false, and as a result the buttons are never disabled. And since these buttons should only be disabled whilst loading anyway, nothing really broke and the app could be used without any issues. What a weird combination of factors....

Ha, yeah that's quite the coincidence. Eslint to the rescue :)

**Comment by ismay** [comment]
So but just to confirm @HendrikThePendric, you're ok with this PR in its current state?

**Comment by HendrikThePendric** [comment]
> So but just to confirm @HendrikThePendric, you're ok with this PR in its current state?
CONFRIMED

**Pull request merged**
