### PR TITLE
fix(i18n): ensure resources are added by importing from index

### PR DESCRIPTION
**Pull request by HendrikThePendric**

### CODE REVIEW

**Comment by mediremi** [comment]
I think a cleaner fix for the linting test is the approach taken in some other apps where we generate translations before running linting (see https://github.com/dhis2/sms-configuration-app/blob/master/.github/workflows/dhis2-verify-app.yml#L79-L80).

**Comment by HendrikThePendric** [comment]
Yeah I know we fixed it like this last time. Later I saw @ismay simply included the comment as I did here. I'd argue that's probably a better fix until we start doing automated e2e tests for translations. This way we are not making the checks in GitHub any take any longer and it's also very clear why this comment is needed. Generating the file just to make the linter happy seems less ideal.

**Review by mediremi — APPROVED** [review]

**Comment by amcgee** [comment]
> Yeah I know we fixed it like this last time. Later I saw @ismay simply included the comment as I did here. I'd argue that's probably a better fix until we start doing automated e2e tests for translations. This way we are not making the checks in GitHub any take any longer and it's also very clear why this comment is needed. Generating the file just to make the linter happy seems less ideal.

I think generating the file is actually the correct approach here - if for some reason the file doesn't exist *the lint will still pass* which is incorrect.  Generating just the translations (not extracting them from source or running a full build) is quite fast, and shouldn't increase any github runtimes as linting runs in parallel with longer jobs.

That being said this looks fine for now, thanks for looking into it 👍   Really glad it wasn't the dual package issue

**Comment by amcgee** [comment]
(of course the proper fix is just to avoid generating source files completely)

**Comment by ismay** [comment]
> > Yeah I know we fixed it like this last time. Later I saw @ismay simply included the comment as I did here. I'd argue that's probably a better fix until we start doing automated e2e tests for translations. This way we are not making the checks in GitHub any take any longer and it's also very clear why this comment is needed. Generating the file just to make the linter happy seems less ideal.
> 
> I think generating the file is actually the correct approach here - if for some reason the file doesn't exist _the lint will still pass_ which is incorrect. Generating just the translations (not extracting them from source or running a full build) is quite fast, and shouldn't increase any github runtimes as linting runs in parallel with longer jobs.
> 
> That being said this looks fine for now, thanks for looking into it 👍 Really glad it wasn't the dual package issue

I agree. That's also the route I went in the end: https://github.com/dhis2/scheduler-app/commit/b14feca1895144b0a093b6e0af8879ac5a007f02#diff-1d835fdd19fc1d6a0129eb898bf4593f444624610ad0ee1311c1a7ae906f70b7R78. Seems more correct and it's doesn't take super long.

**Pull request merged**
