### PR TITLE
fix(user-group): remove users field from form to prevent app freezing

### PR DESCRIPTION
**Pull request by HendrikThePendric**
This is the most minimal implementation we discussed. I have verified that the user-group form is usable now when used with the `https://test.performance.dhis2.org/2.36/`backend.

@amcgee suggested we should possibly also show a read-only paginated table of assigned users. I have omitted that part from the current solution because I actually think that with a little bit of luck we can get the long term solution into the 2.35.2 patch release.

### CODE REVIEW

**Review by amcgee — CHANGES_REQUESTED** [review]
Nice @HendrikThePendric !!  Great to see the form usable again, it works well!

I think we also need to add `!users` to the list of fields requested when loading a userGroup - for really large groups it still downloads 10s of thousands of managed users which aren't needed for anything in the interface.  Because of the backend bug adding `!users` won't improve performance much (the request will still take a long time) but it will save a lot of bandwidth (100s of kbs) and will ensure the performance improves when the API issue is fixed.

Screen Shot 2021-02-18 at 18 57 17

**Comment by HendrikThePendric** [comment]
@amcgee good point! The `users` field is included because we request the `:owner` field. I think now that we have switched to `mergeMode=MERGE` we could probably restrict ourselves to just requesting only the fields we are editing/displaying. However, for the quick fix, just adding `!users` is probably fine, especially because I'm not quite sure which of the other owned fields might be relevant but not part of the form... We definitely need `id` `name` `code` `access` `managedGroups` and `attributeValues`, but perhaps there are more... Anyway, 1d6eaef adds `!users`. So that should be enough for now.

**Review by amcgee — APPROVED** [review]
LGTM!

Maybe @cooper-joe can quickly sign off on the UI change - this is for the "quick fix" with backport to 2.35 for performance reasons.

**Comment by cooper-joe** [comment]
I would add two things:

1. This is quite a difficult message to convey, it's always going to be a bit complex. According to the communication guidelines we should avoid the use of 'you' unless necessary. I suggest updating the text with:
```To add a user to this group, go to the User section and edit the user group settings for a specific user.```

2. I would suggest reducing the visual weight of the box containing the message. While it is important, right now it is weighted as the most important element on the page which I think is not quite true. I'd suggest using a light grey color instead, and reducing the border width.

**Comment by HendrikThePendric** [comment]
Screenshot 2021-02-19 at 12 23 23
I've tweaked things in c158969. Does this look OK to you @cooper-joe?

**Review by cooper-joe — APPROVED** [review]
LGTM 👍 Thanks.

**Pull request merged**
