### PR TITLE
feat(authority-editor): add checkbox for selecting all metadata entities

### PR DESCRIPTION
**Pull request by mediremi**
Closes https://jira.dhis2.org/browse/DHIS2-11853

Commit https://github.com/dhis2/user-app/pull/824/commits/3adabc97b31bb9c7d3090ca8d8ad5f30b1bcfe43 in this PR replaces the custom table styles in the authority editor with the `DataTable` component from `@dhis2/ui`. This is done to fix the following issue with the existing styles:

image

When backporting this fix to 2.37, we may want to skip this commit.

### CODE REVIEW

**Review by Mohammer5 — COMMENTED** [review]
Is this for 2.37?
As we're in a hard freeze, I guess it's not. But I remember @larshelge mentioning this with some sense of urgency.. 

If this is for 2.38, then I think that this should be accompanied by some tests, especially for the `AuthoritySection` class

**Comment by mediremi** [comment]
IIUC, this along with https://jira.dhis2.org/browse/DHIS2-11866 and https://jira.dhis2.org/browse/DHIS2-11865 need to be backported to 2.37. My plan was to merge master into `patch/2.37.0` with permission of the RCB (and `v37`) once this PR is merged and I hear back from @larshelge about https://jira.dhis2.org/browse/DHIS2-11865.

I'll introduce cypress into this app with a test for this functionality :+1:

**Comment by Mohammer5** [comment]
> I'll introduce cypress into this app with a test for this functionality +1

:ok_hand: There's already this PR which has become stale:
https://github.com/dhis2/user-app/pull/710

I guess you could add your changes to that PR, and I'll start working on that one once I have time.

**Review by Mohammer5 — CHANGES_REQUESTED** [review]
I can't select individual checkboxes anymore (in the netlify preview)

**Comment by mediremi** [comment]
> I guess you could add your changes to that PR (after merging this PR without cypress tests), and I'll start working on that one once I have time.

Nice sounds good to me

**Comment by mediremi** [comment]
> I can't select individual checkboxes anymore (in the netlify preview)

Should be fixed by https://github.com/dhis2/user-app/pull/824/commits/44f533f6d298c7088016b5f14e0fcda8c244eb13

**Review by Mohammer5 — CHANGES_REQUESTED** [review]
If I see it correctly, I "Add/Update Private" is disabled and checked when "Add/Update Public" is checked as well.

Change request: Disable the "select all" checkbox for "Add/Update Private" when the "select all" checkbox of "Add/Update Public" is checked

Change request: Deselecting the "select all" checkbox of "Add/Update Private" also deselects the "select all" checkbox of "Delete"

**Comment by mediremi** [comment]
> Change request: Deselecting the "select all" checkbox of "Add/Update Private" also deselects the "select all" checkbox of "Delete"

Selecting a "Add/Update Private" role doesn't currently affect the corresponding "Delete" role - did you mean the "Add/Update Public" role?

**Comment by Mohammer5** [comment]
> Selecting a "Add/Update Private" role doesn't currently affect the corresponding "Delete" role - did you mean the "Add/Update Public" role?

No, I meant ***de***selecting "Add/Update Private" when "Delete" is selected

**Comment by mediremi** [comment]
Ah I see now - if the admin made a mistake by selecting all add/update private roles then they likely do not want the delete roles either?

**Pull request merged**
